# This file is managed by github-terraform. Manual changes will be overwritten.
# To modify it, edit orgs/pantheon-systems/files/dependabot/custom/nextjs-cache-handler.yml
# in https://github.com/pantheon-systems/github-terraform
version: 2
updates:
  # npm - root package
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    groups:
      google-cloud:
        patterns:
          - "@google-cloud/*"
    ignore:
      - dependency-name: "@pantheon-systems/*"

  # npm - example app
  - package-ecosystem: "npm"
    directory: "/example"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "@pantheon-systems/*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
