version: 2
updates:
  # npm - root package
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    groups:
      google-cloud:
        patterns:
          - "@google-cloud/*"
    ignore:
      - dependency-name: "@pantheon-systems/*"

  # npm - example app
  - package-ecosystem: "npm"
    directory: "/example"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "@pantheon-systems/*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    ignore:
      - dependency-name: "pantheon-systems/*"
